"""Check fixed calibration expectations for the MMLU validation sample."""

from collections import Counter
import hashlib
import json

from activation_steering_study.data.mmlu import sample_mmlu


def test_sample_mmlu_retains_calibration_expectations() -> None:
    items = sample_mmlu()

    assert len(items) == 285, "Expected five sampled validation rows from each of 57 subjects"
    subject_counts = Counter(item["subject"] for item in items)
    assert len(subject_counts) == 57 and set(subject_counts.values()) == {5}, (
        "Expected exactly five sampled rows from each MMLU subject"
    )
    assert [items[index]["id"] for index in (0, 1, 2, 142, 284)] == [
        "abstract_algebra_val.csv:0",
        "abstract_algebra_val.csv:1",
        "abstract_algebra_val.csv:4",
        "high_school_psychology_val.csv:43",
        "world_religions_val.csv:18",
    ], "MMLU source IDs differ from the saved calibration sample"
    assert items[0] == {
        "id": "abstract_algebra_val.csv:0",
        "subject": "abstract_algebra",
        "source_index": 0,
        "question": "The cyclic subgroup of Z_24 generated by 18 has order",
        "choices": ["4", "8", "12", "6"],
        "answer": 0,
    }, "The first sampled calibration record changed"
    # This fingerprint records the original 285-row calibration sample.
    assert hashlib.sha256(
        json.dumps(items, ensure_ascii=False).encode("utf-8")
    ).hexdigest() == "9a0651843aceb17a7cc7a2a3c7f508e1d173485247249ae6aae86729bb85d157", (
        "Full MMLU calibration sample changed"
    )
